# Generated by Django 4.2.5 on 2023-10-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Направленность')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('Первичный 1000р', 'Первичный 1000р'), ('Второй 700р', 'Второй 700р')], max_length=20, verbose_name='Прием')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Vetclinika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Ласка')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('summary', models.TextField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='kino',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='ager',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='country',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='director',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='ganre',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='status',
        ),
        migrations.AlterField(
            model_name='director',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='director',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Заболевание'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='AgeRate',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Kino',
        ),
        migrations.AddField(
            model_name='vetclinika',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director'),
        ),
        migrations.AddField(
            model_name='vetclinika',
            name='doct',
            field=models.ManyToManyField(to='catalog.doctor', verbose_name='Врачи'),
        ),
        migrations.AddField(
            model_name='vetclinika',
            name='focus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.focus'),
        ),
        migrations.AddField(
            model_name='vetclinika',
            name='recep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.reception'),
        ),
        migrations.AddField(
            model_name='vetclinika',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.status'),
        ),
        migrations.AddField(
            model_name='vetclinika',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.street'),
        ),
    ]
